### ISSUE TITLE
Introduce changes to generate metadata artifacts

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/app-starters-release#13]
As a developer, I'd like to create a JAR artifact for each task app-starter, so I embed the application metadata and the whitelisted properties in it. 

**Acceptance:**
- the JAR artifact is automatically generated at the build time
- the companion artifact can be used by other clients such as SCDF's shell, dsl and UI
- unit-tests verify the creation and existence of the companion artifact for each task app-starter

**Comment by sobychacko** [comment]
This is completed.
