### ISSUE TITLE
Prepare for Belmont.RC1 release

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/app-starters-release#32]
Following artifacts/apps need to be released as part of Belmont RC1 release train. 

- [x] app starters core - 1.2.0.RC1
- [x] timestamp - 1.2.0.RC1
- [x] jdbchdfs-local - 1.2.0.RC1
- [x] composed-task-runner - 1.0.0.RC1
- [x] spark-client - 1.2.0.RC1
- [x] spark-cluster- 1.2.0.RC1
- [x] spark-yarn- 1.2.0.RC1
- [x] app-starters-release - Belmont.RC1

**Comment by sobychacko** [comment]
All the release tasks for Belmont.RC1 have been completed.
