### ISSUE TITLE
Refactor and polish App READMEs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/app-starters-release#39]
As a developer, I'd like to refactor applicaion READMEs for clarity.

Add Build section
```
== Build
$ ./mvnw clean install -PgenerateApps
$ cd apps

You can then cd into one one of the folders and
build it:

$ ./mvnw clean package
```

**Notes:**
- Whatever we add/polish at each READMEs would directly feed the SCDF reference-docs stories targeted for [1.2.3.RELEASE](https://github.com/spring-cloud/spring-cloud-dataflow/milestone/29). 
- it is an anti-goal to include SCDF DSL samples in each README

**Targeted Apps:**

- [x] timestamp - Glenn
- [x] timestamp-batch - Glenn
- [x] jdbchdfs-local - Glenn
- [x] composed-task-runner - Glenn
- [x] spark-client - Thomas
- [x] spark-cluster - Thomas
- [x] spark-yarn - Thomas

**Comment by trisberg** [comment]
This is a bigger task than just updating the docs. Tried running the `spark-client-task` and had to go all the way back to version 1.0.1.RELEASE to get a build that actually worked. Seems like shifting upstream dependencies influence the way the app works.

**Comment by trisberg** [comment]
Created https://github.com/spring-cloud-task-app-starters/spark-client/issues/5
and https://github.com/spring-cloud-task-app-starters/spark-cluster/issues/4

**Comment by trisberg** [comment]
I have PRs to fix the cluster and client tasks

**Comment by sobychacko** [comment]
All docs issues have been addressed.
