### ISSUE TITLE
Add Spring Boot 2.0 compatibility

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/app-starters-release#45]
As a developer, I'd like to add Spring Boot 2.0 compatibility for the OOTB apps.

**Acceptance:**
- Ensure Spring Boot, Spring Cloud, Spring Cloud Task and the ecosystem is on 2.0 line
- Ensure README/docs are up-to-date
- Ensure tests run successfully

**Targeted Apps:**

- [ ] timestamp @cppwfs  `PR Submited`
- [ ] timestamp-batch @sobychacko  `PR Submited`
- [ ] composed-task-runner  @cppwfs  `PR Submited`
~- [ ] jdbchdfs-local @jvalkeal~
~- [ ] spark-client~
~- [ ] spark-cluster~
~- [ ] spark-yarn~

**Comment by cppwfs** [comment]
Created PR for core to update dependencies for Spring Cloud and Task
Created PR for timestamp.
